# Generated by Django 5.2.17 on 2026-09-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-is_active', '-created_at']},
        ),
        migrations.AddField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
